# Generated by Django 6.0.6 on 2026-07-23 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisky',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('memo', models.TextField(blank=True)),
                ('whisky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiskies.whisky')),
            ],
        ),
    ]
